# 넘파이 사용법 확인

### 기본사용법 패키지 추가
#### 설치
> pip install numpy

### Numpy 버전확인

In [1]:
import numpy as np
print(np.__version__)


1.21.4


### np.array()

In [5]:
# 1차원 배열
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# 2차원 배열
mat = np.array([[10,20,30],[40,50,60]])
print(mat)

[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


In [7]:
# 배열의 타입확인
print(f'arr의 타입 : {type(arr)}')
print(f'mat의 타입 : {type(mat)}')

# 배열의 축(ndim)과 크기(shape) 확인
print(f'arr의 축 : {arr.ndim}')
print(f'arr의 크기 : {arr.shape}')
print(f'mat의 축 : {mat.ndim}')
print(f'mat의 크기 : {mat.shape}')



arr의 타입 : <class 'numpy.ndarray'>
mat의 타입 : <class 'numpy.ndarray'>
arr의 축 : 1
arr의 크기 : (5,)
mat의 축 : 2
mat의 크기 : (2, 3)


In [12]:
#ndarray 초기화 방법
mat_zero = np.zeros([2, 3])
print(mat_zero)

mat_one = np.ones([2, 3])
print(mat_one)

mat_eight = np.full([2, 3], 8)
print(mat_eight)

mat_eye = np.eye(3)
print(mat_eye)

mat_rand = np.random.random([2,3])
print(mat_rand)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[8 8 8]
 [8 8 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.60401332 0.87922728 0.81235333]
 [0.83359204 0.20594759 0.62276732]]
